# -*- coding: utf-8 -*-
from enum import StrEnum


class WorkflowState(StrEnum):
    POLL_STARTING = "POLL_STARTING"
    POLL_OPEN = "POLL_OPEN"
    CLOSE_COMPUTED = "CLOSE_COMPUTED"
    ASSIGNEE_SELECTED = "ASSIGNEE_SELECTED"
    DONE = "DONE"
    FAILED = "FAILED"
    NEEDS_ATTENTION = "NEEDS_ATTENTION"

    # Read-compatible aliases for rows and callers from the pre-v2 workflow.
    POLL_CLOSED = "CLOSE_COMPUTED"
    BOOKING_ASSIGNED = "ASSIGNEE_SELECTED"


class OutboundEffectStatus(StrEnum):
    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"


class OutboundEffectType(StrEnum):
    POLL_OPEN_MESSAGE = "POLL_OPEN_MESSAGE"
    POLL_RESULT_NOTICE = "POLL_RESULT_NOTICE"
    ASSIGNEE_DM = "ASSIGNEE_DM"
    ASSIGNEE_PUBLIC_NOTICE = "ASSIGNEE_PUBLIC_NOTICE"
    CALENDAR_CREATE = "CALENDAR_CREATE"
    BOOKING_DONE_NOTICE = "BOOKING_DONE_NOTICE"
    SCHEDULER_SYNC = "SCHEDULER_SYNC"


class CalendarOutcome(StrEnum):
    CREATED = "CREATED"
    LINK_REQUIRED = "LINK_REQUIRED"
    FAILED = "FAILED"
    UNKNOWN = "UNKNOWN"
